### ISSUE TITLE
Any reason to proceed with loop if right part is out the range?

### ISSUE THREAD

**Issue by vitalk** [ilyaborodin/LeverX_task_2#2]
https://github.com/ilyaborodin/LeverX_task_2/blob/681bac3eb2b8101ed4b5d80b7ea43968edc0ad71/task_2.py#L23

Looks like we should proceed with loop only when left and right items are equal, and should break the loop if right list is exceed. In you case you still looping until left list is over even if nothing change result of the comparison.

**Comment by ilyaborodin** [comment]
This condition will never be fulfilled in my algorithm. He deleted it.
